// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsmeXVATtjMnK2R1DGVJ97CHwHwxAGjPg',
    appId: '1:448383136914:web:3db80c672812c2a7c6a24b',
    messagingSenderId: '448383136914',
    projectId: 'mcqs-flutter-ba6fa',
    authDomain: 'mcqs-flutter-ba6fa.firebaseapp.com',
    storageBucket: 'mcqs-flutter-ba6fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5dJqGXP_dNi8JIuQE-rYoUkxwXAkTVys',
    appId: '1:448383136914:android:5133124f7746396cc6a24b',
    messagingSenderId: '448383136914',
    projectId: 'mcqs-flutter-ba6fa',
    storageBucket: 'mcqs-flutter-ba6fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCrCNFj-Bjxsp0nej6umXdVdjT71aWBXc',
    appId: '1:448383136914:ios:272bfc4126f8e87ac6a24b',
    messagingSenderId: '448383136914',
    projectId: 'mcqs-flutter-ba6fa',
    storageBucket: 'mcqs-flutter-ba6fa.appspot.com',
    iosBundleId: 'com.example.quizAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCrCNFj-Bjxsp0nej6umXdVdjT71aWBXc',
    appId: '1:448383136914:ios:d8cd36e4e1035e80c6a24b',
    messagingSenderId: '448383136914',
    projectId: 'mcqs-flutter-ba6fa',
    storageBucket: 'mcqs-flutter-ba6fa.appspot.com',
    iosBundleId: 'com.example.quizAppFirebase.RunnerTests',
  );
}
